# Generated by Django 4.2.29 on 2026-04-07 17:07

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmbeddingTerm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('term', models.CharField(db_index=True, help_text='Dictionary term name (e.g., "RemessaAquisicao")', max_length=255, unique=True)),
                ('prefix', models.CharField(choices=[('biz', 'Business'), ('sys', 'System')], help_text='Domain: business or system infrastructure', max_length=10)),
                ('composed_text', models.TextField(help_text='Rich text composed from term metadata (description, aliases, edges)')),
                ('vector', django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(), help_text='768-dimensional embedding vector (Gemini)', size=None)),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Last time embedding was updated')),
            ],
            options={
                'db_table': 'embedding_term',
                'indexes': [models.Index(fields=['term'], name='embedding_term_term__idx'), models.Index(fields=['prefix'], name='embedding_term_prefix__idx')],
            },
        ),
        migrations.CreateModel(
            name='EmbeddingAnchor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(db_index=True, help_text='Code symbol name (class, function, etc.)', max_length=255, unique=True)),
                ('term', models.CharField(blank=True, help_text='Dictionary term this symbol implements (null if untagged)', max_length=255, null=True)),
                ('file', models.CharField(help_text='Source file path relative to repo root', max_length=500)),
                ('line', models.IntegerField(help_text='Line number where symbol is defined')),
                ('composed_text', models.TextField(help_text='Rich text composed from symbol location, term, and description')),
                ('vector', django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(), help_text='768-dimensional embedding vector (Gemini)', size=None)),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Last time embedding was updated')),
            ],
            options={
                'db_table': 'embedding_anchor',
                'indexes': [models.Index(fields=['symbol'], name='embedding_anchor_symbol__idx'), models.Index(fields=['term'], name='embedding_anchor_term__idx'), models.Index(fields=['file'], name='embedding_anchor_file__idx')],
            },
        ),
    ]
