"""
Embedding database models for the ontology tool.

These Django models persist semantic vectors for terms and code anchors.
They enable pgvector-based semantic search over the operational ontology.

Authority: Gemini Text Embedding API (768-dim vectors)
Persistence: PostgreSQL with pgvector extension
"""

from django.db import models
from django.contrib.postgres.fields import ArrayField


class EmbeddingTerm(models.Model):
    """
    Vector embeddings for dictionary terms.

    Enables semantic search: "How does kit matching work?" -> cosine similarity
    against term embeddings returns KitType, FilterResult, etc.

    Generated by: tools/semantic-index/embeddings/ pipeline
    Authority: dictionary-business.md, dictionary-sys.md
    """

    term = models.CharField(
        max_length=255,
        unique=True,
        db_index=True,
        help_text='Dictionary term name (e.g., "RemessaAquisicao")',
    )
    prefix = models.CharField(
        max_length=10,
        choices=[('biz', 'Business'), ('sys', 'System')],
        help_text='Domain: business or system infrastructure',
    )
    composed_text = models.TextField(
        help_text='Rich text composed from term metadata (description, aliases, edges)',
    )
    vector = ArrayField(
        models.FloatField(),
        help_text='768-dimensional embedding vector (Gemini)',
    )
    updated_at = models.DateTimeField(
        auto_now=True,
        help_text='Last time embedding was updated',
    )

    class Meta:
        db_table = 'embedding_term'
        app_label = 'personal_assistant'
        indexes = [
            models.Index(fields=['term'], name='embedding_term_term__idx'),
            models.Index(fields=['prefix'], name='embedding_term_prefix__idx'),
        ]

    def __str__(self):
        return f"{self.term} [{self.prefix}]"


class EmbeddingAnchor(models.Model):
    """
    Vector embeddings for code anchors (tagged symbols).

    Enables discovery: "What code implements RemessaAquisicao?" -> cosine
    similarity returns RemessaAquisicaoUseCase, approve_remessa, etc.

    Generated by: tools/semantic-index/embeddings/ pipeline
    Authority: @biz/@sys tags in code
    """

    symbol = models.CharField(
        max_length=255,
        unique=True,
        db_index=True,
        help_text='Code symbol name (class, function, etc.)',
    )
    term = models.CharField(
        max_length=255,
        null=True,
        blank=True,
        help_text='Dictionary term this symbol implements (null if untagged)',
    )
    file = models.CharField(
        max_length=500,
        help_text='Source file path relative to repo root',
    )
    line = models.IntegerField(
        help_text='Line number where symbol is defined',
    )
    composed_text = models.TextField(
        help_text='Rich text composed from symbol location, term, and description',
    )
    vector = ArrayField(
        models.FloatField(),
        help_text='768-dimensional embedding vector (Gemini)',
    )
    updated_at = models.DateTimeField(
        auto_now=True,
        help_text='Last time embedding was updated',
    )

    class Meta:
        db_table = 'embedding_anchor'
        app_label = 'personal_assistant'
        indexes = [
            models.Index(fields=['symbol'], name='embedding_anchor_symbol__idx'),
            models.Index(fields=['term'], name='embedding_anchor_term__idx'),
            models.Index(fields=['file'], name='embedding_anchor_file__idx'),
        ]

    def __str__(self):
        return f"{self.symbol} ({self.file}:{self.line})"
